import Footer from "@/components/Footer";
import Head from "next/head";
import Link from "next/link";
import { useState } from "react";
import { addCampaign, getLastCampaignId } from "@/services/Web3Service";

export default function Donate() {
  const [campaign, setCampaign] = useState({});
  const [message, setMessage] = useState("");

  function onInputChange(evt) {
    setCampaign(prevState => ({ ...prevState, [evt.target.id]: evt.target.value }));
  }

  function btnSaveClick() {
    setMessage("Salvando...");
    addCampaign(campaign)
      .then(tx => getLastCampaignId())
      .then(id => setMessage(`Campanha salva com ID <b>${id}</b>. Avise seus amigos e passe a eles esse número.`))
      .catch(err => {
        setMessage(err.message);
        console.log(err);
      });
  }
  
  return (
    <>
      <Head>
        <title>Donate Crypto | Criar Campanha</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <div className="container">
        <h1 className="display-5 fw-bold text-body-emphasis lh-1 mb-3">Donate Crypto</h1>
        <p>Preencha os campos para incluir sua campanha na plataforma.</p>
        <hr className="mb-4" />
        <div className="col-6">
          <div className="form-floating mb-3">
            <input type="text" id="title" name="title" className="form-control" value={campaign.title} onChange={onInputChange} />
            <label htmlFor="title">Título</label>
          </div>

          <div className="form-floating mb-3">
            <textarea id="description" name="description" className="form-control" value={campaign.description} onChange={onInputChange} />
            <label htmlFor="description">Descrição</label>
          </div>

          <div className="form-floating mb-3">
            <input type="text" id="imageUrl" name="imageUrl" className="form-control" value={campaign.imageUrl} onChange={onInputChange} />
            <label htmlFor="imageUrl">URL da Imagem:</label>
          </div>

          <div className="form-floating mb-3">
            <input type="text" id="videoUrl" name="videoUrl" className="form-control" value={campaign.videoUrl} onChange={onInputChange} />
            <label htmlFor="videoUrl">URL do Vídeo:</label>
          </div>
        </div>

        <div className="col-6 mb-3">
          <input type="button" value="Salvar Campanha" className="btn btn-primary col-12 p-3" onClick={btnSaveClick} />
        </div>

        <div className="col-6 mb-3">
          <Link href="/" className="btn btn-secondary col-12 p-3">Voltar</Link>
        </div>

        {message && <div className="alert alert-success p-3 col-6" role="alert">{message}</div>}

        <Footer />
      </div>
    </>
  );
}